import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Import Font Awesome
// import '@fortawesome/fontawesome-free/css/all.min.css';

// ⚠️ IMPORTANT: Import addIcons and icons BEFORE bootstrap
import { addIcons } from 'ionicons';
import { 
  // Navigation
  menuOutline,
  closeOutline,
  chevronBackOutline,
  chevronForwardOutline,
  chevronDownOutline,
  arrowForwardOutline,
  
  // Home & Layout
  homeOutline,
  homeSharp,
  gridOutline,
  gridSharp,
  
  // Room & Accommodation
  bedOutline,
  bedSharp,
  locationOutline,
  locationSharp,
  wifiOutline,
  wifiSharp,
  carOutline,
  carSharp,
  tvOutline,
  tvSharp,
  sparklesOutline,
  sparklesSharp,
  personOutline,
  personSharp,
  peopleOutline,
  peopleSharp,
  waterOutline,
  waterSharp,
  restaurantOutline,
  restaurantSharp,
  snowOutline,
  cafeOutline,
  lockClosedOutline,
  briefcaseOutline,
  peopleCircleOutline,
  squareOutline,
  businessOutline,
  
  // Social Media
  logoWhatsapp,
  logoInstagram,
  logoFacebook,
  logoTwitter,
  logoTiktok,
  
  // Contact
  callOutline,
  callSharp,
  mailOutline,
  mailSharp,
  
  // FAQ & Forms
  addOutline,
  removeOutline,
  addSharp,
  removeSharp,
  
  // Sections
  informationCircleOutline,
  informationCircleSharp,
  imagesOutline,
  imagesSharp,
  cashOutline,
  cashSharp,
  mapOutline,
  mapSharp,
  helpCircleOutline,
  helpCircleSharp,
  sendOutline,
  sendSharp,
  calendarOutline,
  calendarSharp,
  starOutline,
  starSharp,
  playOutline,
  pauseOutline,
  
  // Security
  shieldCheckmarkOutline,
  shieldCheckmarkSharp,
  
  // Additional Icons
  checkmarkCircleOutline,
  checkmarkCircle,
  chevronUpOutline,
  arrowBackOutline,
  searchOutline,
  filterOutline,
  heartOutline,
  shareOutline,
  bookmarkOutline,
  timeOutline,
  eyeOutline,
  folderOutline,
  chatbubbleOutline,
  gameControllerOutline,
  bookOutline,
  leafOutline,
  compassOutline,
  giftOutline,
  alertCircleOutline,
  
  // Solid Icons
  add,
  remove,
  close,
  closeCircle,
  checkmark,
  alert,
  information,
  help,
  send,
  map,
  heart,
  share,
  bookmark,
  time,
  calendar,
  person,
  mail,
  call,
  search,
  filter,
  star,
  location,
  bed,
  people,
  water,
  wifi,
  car,
  tv,
  restaurant,
  sparkles,
  chevronDown,
  chevronUp,
  arrowForward,
  arrowBack,
  menu,
  snow,
  cafe,
  lockClosed,
  briefcase,
  eye,
  folder,
  chatbubble,
  gameController,
  book,
  leaf,
  compass,
  gift,
  
  // Sharp variants
  menuSharp,
  closeSharp,
  arrowForwardSharp,
  chevronDownSharp,
  checkmarkSharp,
} from 'ionicons/icons';

// ⚠️ REGISTER ALL ICONS BEFORE BOOTSTRAPPING
addIcons({
  // Navigation
  'menu-outline': menuOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'close-outline': closeOutline,
  
  // Home & Layout
  'home-outline': homeOutline,
  'home-sharp': homeSharp,
  'grid-outline': gridOutline,
  'grid-sharp': gridSharp,
  
  // Room & Accommodation
  'bed-outline': bedOutline,
  'bed-sharp': bedSharp,
  'location-outline': locationOutline,
  'location-sharp': locationSharp,
  'wifi-outline': wifiOutline,
  'wifi-sharp': wifiSharp,
  'car-outline': carOutline,
  'car-sharp': carSharp,
  'tv-outline': tvOutline,
  'tv-sharp': tvSharp,
  'sparkles-outline': sparklesOutline,
  'sparkles-sharp': sparklesSharp,
  'person-outline': personOutline,
  'person-sharp': personSharp,
  'people-outline': peopleOutline,
  'people-sharp': peopleSharp,
  'water-outline': waterOutline,
  'water-sharp': waterSharp,
  'restaurant-outline': restaurantOutline,
  'restaurant-sharp': restaurantSharp,
  'snow-outline': snowOutline,
  'cafe-outline': cafeOutline,
  'lock-closed-outline': lockClosedOutline,
  'briefcase-outline': briefcaseOutline,
  'people-circle-outline': peopleCircleOutline,
  'square-outline': squareOutline,
  'business-outline': businessOutline,
  
  // Social Media
  'logo-whatsapp': logoWhatsapp,
  'logo-instagram': logoInstagram,
  'logo-facebook': logoFacebook,
  'logo-twitter': logoTwitter,
  'logo-tiktok': logoTiktok,
  
  // Contact
  'call-outline': callOutline,
  'call-sharp': callSharp,
  'mail-outline': mailOutline,
  'mail-sharp': mailSharp,
  
  // FAQ & Forms
  'add-outline': addOutline,
  'remove-outline': removeOutline,
  'add-sharp': addSharp,
  'remove-sharp': removeSharp,
  
  // Sections
  'information-circle-outline': informationCircleOutline,
  'information-circle-sharp': informationCircleSharp,
  'images-outline': imagesOutline,
  'images-sharp': imagesSharp,
  'cash-outline': cashOutline,
  'cash-sharp': cashSharp,
  'map-outline': mapOutline,
  'map-sharp': mapSharp,
  'help-circle-outline': helpCircleOutline,
  'help-circle-sharp': helpCircleSharp,
  'send-outline': sendOutline,
  'send-sharp': sendSharp,
  'calendar-outline': calendarOutline,
  'calendar-sharp': calendarSharp,
  'star-outline': starOutline,
  'star-sharp': starSharp,
  'play-outline': playOutline,
  'pause-outline': pauseOutline,
  
  // Security
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'shield-checkmark-sharp': shieldCheckmarkSharp,
  
  // Additional Outline Icons
  'checkmark-circle-outline': checkmarkCircleOutline,
  'chevron-up-outline': chevronUpOutline,
  'arrow-back-outline': arrowBackOutline,
  'search-outline': searchOutline,
  'filter-outline': filterOutline,
  'heart-outline': heartOutline,
  'share-outline': shareOutline,
  'bookmark-outline': bookmarkOutline,
  'time-outline': timeOutline,
  'eye-outline': eyeOutline,
  'folder-outline': folderOutline,
  'chatbubble-outline': chatbubbleOutline,
  'game-controller-outline': gameControllerOutline,
  'book-outline': bookOutline,
  'leaf-outline': leafOutline,
  'compass-outline': compassOutline,
  'gift-outline': giftOutline,
  'alert-circle-outline': alertCircleOutline,
  
  // Solid Icons
  'add': add,
  'remove': remove,
  'close': close,
  'close-circle': closeCircle,
  'checkmark': checkmark,
  'checkmark-circle': checkmarkCircle,
  'alert': alert,
  'information': information,
  'help': help,
  'send': send,
  'map': map,
  'heart': heart,
  'share': share,
  'bookmark': bookmark,
  'time': time,
  'calendar': calendar,
  'person': person,
  'mail': mail,
  'call': call,
  'search': search,
  'filter': filter,
  'star': star,
  'location': location,
  'bed': bed,
  'people': people,
  'water': water,
  'wifi': wifi,
  'car': car,
  'tv': tv,
  'restaurant': restaurant,
  'sparkles': sparkles,
  'chevron-down': chevronDown,
  'chevron-up': chevronUp,
  'arrow-forward': arrowForward,
  'arrow-back': arrowBack,
  'menu': menu,
  'snow': snow,
  'cafe': cafe,
  'lock-closed': lockClosed,
  'briefcase': briefcase,
  'eye': eye,
  'folder': folder,
  'chatbubble': chatbubble,
  'game-controller': gameController,
  'book': book,
  'leaf': leaf,
  'compass': compass,
  'gift': gift,
  
  // Sharp Icons
  'menu-sharp': menuSharp,
  'close-sharp': closeSharp,
  'arrow-forward-sharp': arrowForwardSharp,
  'chevron-down-sharp': chevronDownSharp,
  'checkmark-sharp': checkmarkSharp,
});

// ⚠️ BOOTSTRAP AFTER ICONS ARE REGISTERED
bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
  ],
});